language: python

addons:
  hosts:
    - preview

python:
  - "3.6"

sudo: required

services:
  - docker

install:
  - echo "${TRAVIS_BRANCH}"
  - pip3 install aiohttp

before_script:
  - make build-cache
  - make start-test

script:
  - make test

after_script:
  - make end-test

after_success:
  - make tag TAG=latest
  - make push TAG=latest
  - make tag TAG=${TRAVIS_COMMIT::7}
  - make push TAG=${TRAVIS_COMMIT::7}
