version: '3'
services:
  preview-server:
    image: btimby/preview-server
    volumes:
      - ./fixtures:/mnt/files:ro
      - /tmp/preview:/mnt/store
      - ./:/app:ro
    tmpfs:
      - /tmp
    environment:
      - VIRTUAL_HOST=preview
      - VIRTUAL_PORT=3000
      - PVS_X_ACCEL_REDIRECT=/internal/preview
      - PVS_STORE=/mnt/store
      - PVS_UID=101
      - PVS_GID=101
      - PVS_LOGLEVEL=DEBUG
      - PVS_HTTP_LOGLEVEL=INFO
      - PVS_SOFFICE_ADDR=haproxy
      - PVS_SOFFICE_PORT=2002
      - PVS_METRICS=on
      - PVS_RELOAD=on

  soffice-server:
    image: btimby/preview-soffice
    volumes:
      - ./fixtures:/mnt/files:ro
    tmpfs:
      - /tmp
    environment:
      - PVS_SOFFICE_ADDR=0.0.0.0
      - PVS_SOFFICE_PORT=2002

  nginx:
    image: jwilder/nginx-proxy
    ports:
      - 3000:80
    volumes:
      - ./fixtures:/mnt/files:ro
      - /tmp/preview:/mnt/store
      - ./docker/nginx/preview_location:/etc/nginx/vhost.d/preview_location:ro
      - ./docker/nginx/preview:/etc/nginx/vhost.d/preview:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  haproxy:
    image: haproxy
    ports:
      - 3001:8080
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    ports:
      - 3002:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro
      - ./docker/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./docker/grafana/preview-server-dashboard.json:/etc/grafana/provisioning/dashboards/preview-server-dashboard.json:ro
