version: '3'

volumes:
  previews:

networks:
  shared:
    external:
      name: shared
    
services:
  preview-server:
    image: btimby/preview-server
    volumes:
      - ./fixtures:/mnt/files:ro
      - ./:/app:ro
      - previews:/mnt/store
    labels:
      - autoheal=true
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 0
    networks:
      - shared
    tmpfs:
      - /tmp
    environment:
      - PVS_STORE=/mnt/store
      - PVS_STORE_MAX_AGE=1h
#      - PVS_UID=101
#      - PVS_GID=101
      - PVS_LOGLEVEL=DEBUG
      - PVS_HTTP_LOGLEVEL=INFO
      - PVS_SOFFICE_ADDR=haproxy
      - PVS_SOFFICE_PORT=2002
      - PVS_METRICS=on
      - PVS_RELOAD=on

  soffice-server:
    image: btimby/preview-soffice
    volumes:
      - ./fixtures:/mnt/files:ro
    labels:
      - autoheal=true
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'Hello world' | unoconv --server=127.0.0.1 --port=2002 --stdin --stdout > /dev/null"]
      interval: 30s
      timeout: 10s
      retries: 0
    networks:
      - shared
    tmpfs:
      - /tmp
    environment:
      - PVS_SOFFICE_ADDR=0.0.0.0
      - PVS_SOFFICE_PORT=2002

  haproxy:
    image: haproxy:2.1
    networks:
      - shared
    ports:
      - 3000:3000
      - 3001:8080
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  autoheal:
    image: willfarrell/autoheal
    restart: always
    networks:
      - shared
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
