version: '3'
services:
  preview-server:
    image: btimby/preview-server
    volumes:
      - ./fixtures:/mnt/files:ro
      - /tmp/preview:/mnt/store
    command: preview
    environment:
      - VIRTUAL_HOST=preview
      - VIRTUAL_PORT=3000
      - PVS_X_ACCEL_REDIRECT=/internal/preview
#      - PVS_STORE=/mnt/store
      - PVS_UID=101
      - PVS_GID=101
      - PVS_LOGLEVEL=INFO
      - PVS_SOFFICE_ADDR=haproxy
      - PVS_METRICS=on

  soffice-server:
    image: btimby/preview-server
    volumes:
      - ./fixtures:/mnt/files:ro
    command: soffice
    environment:
      - PVS_SOFFICE_ADDR=0.0.0.0

  nginx:
    image: jwilder/nginx-proxy
    ports:
      - 8080:80
    volumes:
      - ./fixtures:/mnt/files:ro
      - /tmp/preview:/mnt/store
      - ./docker/nginx/preview_location:/etc/nginx/vhost.d/preview_location:ro
      - ./docker/nginx/preview:/etc/nginx/vhost.d/preview:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  haproxy:
    image: haproxy
    ports:
      - 8082:8080
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro
      - ./docker/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./docker/grafana/preview-server-dashboard.json:/etc/grafana/provisioning/dashboards/preview-server-dashboard.json:ro
