version: '3'

services:
  preview-server:
    image: btimby/preview-server
    volumes:
      - ./fixtures:/mnt/files:ro
      - ./:/app:ro
    labels:
      - autoheal
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 0
    tmpfs:
      - /tmp
    environment:
      - PVS_X_ACCEL_REDIRECT=/internal/preview
      - PVS_STORE=/tmp
#      - PVS_UID=101
#      - PVS_GID=101
      - PVS_LOGLEVEL=WARNING
      - PVS_HTTP_LOGLEVEL=WARNING
      - PVS_SOFFICE_ADDR=haproxy
      - PVS_SOFFICE_PORT=2002
      - PVS_METRICS=on

  soffice-server:
    image: btimby/preview-soffice
    volumes:
      - ./fixtures:/mnt/files:ro
    labels:
      - autoheal
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'Hello world' | unoconv --server=127.0.0.1 --port=2002 --stdin --stdout > /dev/null"]
      interval: 30s
      timeout: 10s
      retries: 0
    tmpfs:
      - /tmp
    environment:
      - PVS_SOFFICE_ADDR=0.0.0.0
      - PVS_SOFFICE_PORT=2002

  haproxy:
    image: haproxy:2.1
    ports:
      - 3000:3000
      - 3001:8080
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    ports:
      - 3002:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro
      - ./docker/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./docker/grafana/preview-server-dashboard.json:/etc/grafana/provisioning/dashboards/preview-server-dashboard.json:ro

  autoheal:
    image: willfarrell/autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
