version: '3'

volumes:
  previews:

services:
  preview-server:
    image: btimby/preview-server
    volumes:
      - ./fixtures:/mnt/files:ro
      - previews:/mnt/store
    tmpfs:
      - /tmp
    ports:
      - 3000:3000
    environment:
      - PVS_STORE=/mnt/store
#      - PVS_UID=101
#      - PVS_GID=101
      - PVS_LOGLEVEL=WARNING
      - PVS_HTTP_LOGLEVEL=INFO
      - PVS_SOFFICE_ADDR=haproxy
      - PVS_SOFFICE_PORT=2002
      - PVS_METRICS=off

  soffice-server:
    image: btimby/preview-soffice
    volumes:
      - ./fixtures:/mnt/files:ro
    labels:
      - autoheal
    healthcheck:
      test: ["CMD", "timeout", "10", "bash", "-c", "echo 'Hello world' | unoconv --server=127.0.0.1 --port=2002 --stdin --stdout > /dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 0
    tmpfs:
      - /tmp
    environment:
      - PVS_SOFFICE_ADDR=0.0.0.0
      - PVS_SOFFICE_PORT=2002

  haproxy:
    image: haproxy:2.1
    ports:
      - 3001:8080
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  autoheal:
    image: willfarrell/autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
