version: '3'
services:
  preview-server:
    image: btimby/preview-server
    volumes:
      - ./fixtures:/mnt/files:ro
      - /tmp/preview:/mnt/store
    ports:
      - 3000:3000
    tmpfs:
      - /tmp
    environment:
      - PVS_STORE=/mnt/store
      - PVS_UID=101
      - PVS_GID=101
      - PVS_LOGLEVEL=WARNING
      - PVS_HTTP_LOGLEVEL=DEBUG
      - PVS_SOFFICE_ADDR=soffice-server
      - PVS_SOFFICE_PORT=2002
      - PVS_METRICS=off

  soffice-server:
    image: btimby/preview-soffice
    volumes:
      - ./fixtures:/mnt/files:ro
    tmpfs:
      - /tmp
    environment:
      - PVS_SOFFICE_ADDR=0.0.0.0
      - PVS_SOFFICE_PORT=2002
