version: '3'

volumes:
  previews:

networks:
  shared:
    external:
      name: shared

services:
  preview-server:
    image: btimby/preview-server
    volumes:
      - ./fixtures:/mnt/files:ro
      - ./:/app:ro
      - previews:/mnt/store
    labels:
      - autoheal=true
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 0
    networks:
      - shared
    ports:
      - 3000:3000
    tmpfs:
      - /tmp
    environment:
      - PVS_STORE=/mnt/store
#      - PVS_UID=101
#      - PVS_GID=101
      - PVS_LOG_LEVEL=DEBUG
      - PVS_HTTP_LOG_LEVEL=DEBUG
      - PVS_SOFFICE_ADDR=soffice-server
      - PVS_SOFFICE_PORT=2002
      - PVS_METRICS=off
      - PVS_MAX_OFFICE_WORKERS=1

  soffice-server:
    image: btimby/preview-soffice
    volumes:
      - ./fixtures:/mnt/files:ro
    labels:
      - autoheal=true
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'Hello world' | unoconv --server=127.0.0.1 --port=2002 --stdin --stdout > /dev/null"]
      interval: 30s
      timeout: 10s
      retries: 0
    networks:
      - shared
    tmpfs:
      - /tmp
    environment:
      - PVS_SOFFICE_ADDR=0.0.0.0
      - PVS_SOFFICE_PORT=2002

  autoheal:
    image: willfarrell/autoheal
    restart: always
    networks:
      - shared
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
