{
 "title": "Preview server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Conversions by format",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pvs_conversion_time_secs_count[1m])) by (format)",
     "legendFormat": "{{format}}"
    }
   ]
  },
  {
   "title": "Conversion time by format",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pvs_conversion_time_secs_sum[1m])) by (format) / sum(rate(pvs_conversion_time_secs_count[1m])) by (format)",
     "legendFormat": "{{format}}"
    }
   ]
  },
  {
   "title": "Conversions by backend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pvs_conversion_time_secs_count[1m])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Conversion time by backend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pvs_conversion_time_secs_sum[1m])) by (backend) / sum(rate(pvs_conversion_time_secs_count[1m])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Preview requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aiohttp_request_in_progress{endpoint='/preview/'})",
     "legendFormat": "Requests in progress"
    },
    {
     "expr": "sum(rate(aiohttp_request_total{endpoint='/preview/'}[1m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Conversion errors by backend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pvs_conversion_errors_total) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Preview request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance) (rate(aiohttp_request_latency_secs_sum{endpoint='/preview/'}[1m]) / rate(aiohttp_request_latency_secs_count{endpoint='/preview/'}[1m]))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Storage operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pvs_storage_operations_total[1m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Store usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 24 },
   "targets": [
    {
     "expr": "sum(pvs_storage_bytes_total) / 1024 / 1024",
     "legendFormat": "MiB"
    },
    { "expr": "sum(pvs_storage_files_total)", "legendFormat": "files" }
   ]
  }
 ]
}