#!/bin/bash

RESTART_FLAG=/tmp/restart

if [ "${PVS_RELOAD}" == "" ]; then
    exit 0
fi

touch ${RESTART_FLAG}

read -d '' CMD << EOF
inotifywait -mqr -e close_write "/app/preview" | while read line
do
    echo "Application code changed, touching ${RESTART_FLAG}"
    touch -m ${RESTART_FLAG}
done
EOF

echo "Starting preview-restart" > /proc/1/fd/1

exec -a restart bash -c "${CMD} 1> /proc/1/fd/1 2> /proc/1/fd/2" &
