#!/bin/bash

# wrapper script for unoconv to filter annoying messages from soffice.bin

export HOME=/tmp

echo "Starting unoconv..."
while true;
do
    /usr/local/bin/unoconv $@ 2>&1 | grep -v func=xmlSecCheckVersionExt

    echo "Restarting unoconv..."
    sleep 1
done
