#!/bin/bash

# wrapper script for unoconv to filter annoying messages from soffice.bin

export HOME=/tmp

while true;
do
    /usr/local/bin/unoconv $@ 2>&1 | grep -v func=xmlSecCheckVersionExt

    echo "Respawning unoconv..."
    sleep 1
done
